language: node_js
node_js:
  - lts/*
  - node
    #before_install:
    #  - npm i -g npm@version-number

script: echo "Running tests against $(node -v)"

jobs:
  include:
    - stage: formatting
      script: npm run format
    - stage: npm release
      #node_js: "7"
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release
    - stage: unit test one
      script: echo one
    - stage: unit test two
      script: echo two
    - stage: deploy
      script: echo deploy script
